name: Check
on:
  push:
    branches: [ "development" ]    
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci 
      - run: npm run lint
  Check:
    runs-on : ubuntu-latest
    needs: [Build,Lint]
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ secrets.TOKEN }}
          source_ref: 'development'
          target_branch: 'main'
          commit_message_template: '[Merge]チェック完了'